#!/usr/bin/env python

import os
from platform import machine
import sys
from buildfarm.mock_root import check_mock_config, get_default_confdir

def parse_options():
    import argparse
    parser = argparse.ArgumentParser(description='Verifies and if necessary, creates mock configuration')
    parser.add_argument('--output-dir', default=get_default_confdir(),
                        help='Location to store mock config(s). Default: %(default)s')
    parser.add_argument('--arch', default=machine(),
                        help='Target architecture (i386, x86_64, srpm). Default: %(default)s')
    parser.add_argument('distro',
                        help='Distribution to configure (heisenbug, etc).')
    parser.add_argument('--use-ramdisk', default=False, action='store_true',
                        help='Enable to use a ramdisk for builds. Default: %(default)s')
    parser.add_argument('--quiet', default=False, action='store_true',
                        help='Enable to suppress output. Default: %(default)s')
    parser.add_argument('--get-default-output-dir', default=False, action='store_true',
                        help='Prints the default output directory and exits.')
    parser.add_argument('--base', default=None,
                        help='Name of or path to the base mock configuration.')
    args = parser.parse_args()

    return args

if __name__ == "__main__":
    args = parse_options()

    if args.get_default_output_dir:
        print(get_default_confdir())
        sys.exit(0)

    if not args.distro:
        print("Invalid Fedora distribution: %s" % args.distro)
        sys.exit(1)

    check_mock_config(args.distro, args.arch, args.use_ramdisk, args.quiet, args.output_dir, base=args.base)
